Import pandas module.

In [14]:
import pandas as pd
import numpy as np

Load the dataset into a dataframe.

In [32]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")

## Finding duplicates

In this section you will identify duplicate values in the dataset.

Find how many duplicate rows exist in the dataframe.

In [23]:
# your code goes here
df[df.duplicated()]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
1168,2339,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1169,2342,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,Some college/university study without earning ...,"Information systems, information technology, o...",...,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Too long,Easy
1170,2343,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,Canada,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,27.0,Man,No,Straight / Heterosexual,Black or of African descent;White or of Europe...,No,Appropriate in length,Neither easy nor difficult
1171,2344,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
1172,2347,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,NaN,Woman,No,Straight / Heterosexual,Biracial,No,Too long,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2297,4674,"I am not primarily a developer, but I write co...",Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,Bangladesh,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,31.0,Man,No,Bisexual;Gay or Lesbian;Straight / Heterosexual,Black or of African descent;Hispanic or Latino...,Yes,Too long,Neither easy nor difficult
2298,4675,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,Just as welcome now as I felt last year,Tech meetups or events in your area,27.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
2299,4676,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Finland,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...",...,Somewhat less welcome now than last year,NaN,36.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
2300,4677,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United Kingdom,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...",...,Just as welcome now as I felt last year,NaN,40.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
2301,4679,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,NaN,27.0,Man,No,NaN,White or of European descent,No,Appropriate in length,Easy

In [33]:
df['Respondent'].duplicated().value_counts()

False    11398
True       154
Name: Respondent, dtype: int64

In [34]:
df.duplicated().value_counts()

False    11398
True       154
dtype: int64

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [35]:
# your code goes here
df.drop_duplicates(keep='first', inplace=True)

Verify if duplicates were actually dropped.

In [36]:
# your code goes here
df.duplicated().value_counts()

False    11398
dtype: int64

In [37]:
df['Respondent'].duplicated().value_counts()

False    11398
Name: Respondent, dtype: int64

In [29]:
df.shape

(11305, 85)

## Finding Missing values

Find the missing values for all columns.

In [10]:
# your code goes here
missing_data = df.isnull()

for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

Respondent
False    11305
Name: Respondent, dtype: int64

MainBranch
False    11305
Name: MainBranch, dtype: int64

Hobbyist
False    11305
Name: Hobbyist, dtype: int64

OpenSourcer
False    11305
Name: OpenSourcer, dtype: int64

OpenSource
False    11224
True        81
Name: OpenSource, dtype: int64

Employment
False    11305
Name: Employment, dtype: int64

Country
False    11305
Name: Country, dtype: int64

Student
False    11255
True        50
Name: Student, dtype: int64

EdLevel
False    11195
True       110
Name: EdLevel, dtype: int64

UndergradMajor
False    10570
True       735
Name: UndergradMajor, dtype: int64

EduOther
False    11141
True       164
Name: EduOther, dtype: int64

OrgSize
False    11210
True        95
Name: OrgSize, dtype: int64

DevType
False    11241
True        64
Name: DevType, dtype: int64

YearsCode
False    11296
True         9
Name: YearsCode, dtype: int64

Age1stCode
False    11292
True        13
Name: Age1stCode, dtype: int64

YearsCodePro
False    11289
True        16
Name: YearsCodePro, dtype: int64

CareerSat
False    11305
Name: CareerSat, dtype: int64

JobSat
False    11304
True         1
Name: JobSat, dtype: int64

MgrIdiot
False    10815
True       490
Name: MgrIdiot, dtype: int64

MgrMoney
False    10811
True       494
Name: MgrMoney, dtype: int64

MgrWant
False    10815
True       490
Name: MgrWant, dtype: int64

JobSeek
False    11305
Name: JobSeek, dtype: int64

LastHireDate
False    11305
Name: LastHireDate, dtype: int64

LastInt
False    10898
True       407
Name: LastInt, dtype: int64

FizzBuzz
False    11268
True        37
Name: FizzBuzz, dtype: int64

JobFactors
False    11302
True         3
Name: JobFactors, dtype: int64

ResumeUpdate
False    11268
True        37
Name: ResumeUpdate, dtype: int64

CurrencySymbol
False    11305
Name: CurrencySymbol, dtype: int64

CurrencyDesc
False    11305
Name: CurrencyDesc, dtype: int64

CompTotal
False    10500
True       805
Name: CompTotal, dtype: int64

CompFreq
False    11099
True       206
Name: CompFreq, dtype: int64

ConvertedComp
False    10493
True       812
Name: ConvertedComp, dtype: int64

WorkWeekHrs
False    11185
True       120
Name: WorkWeekHrs, dtype: int64

WorkPlan
False    11185
True       120
Name: WorkPlan, dtype: int64

WorkChallenge
False    11143
True       162
Name: WorkChallenge, dtype: int64

WorkRemote
False    11297
True         8
Name: WorkRemote, dtype: int64

WorkLoc
False    11273
True        32
Name: WorkLoc, dtype: int64

ImpSyn
False    11300
True         5
Name: ImpSyn, dtype: int64

CodeRev
False    11304
True         1
Name: CodeRev, dtype: int64

CodeRevHrs
False    8905
True     2400
Name: CodeRevHrs, dtype: int64

UnitTests
False    11276
True        29
Name: UnitTests, dtype: int64

PurchaseHow
False    11110
True       195
Name: PurchaseHow, dtype: int64

PurchaseWhat
False    11267
True        38
Name: PurchaseWhat, dtype: int64

LanguageWorkedWith
False    11294
True        11
Name: LanguageWorkedWith, dtype: int64

LanguageDesireNextYear
False    11173
True       132
Name: LanguageDesireNextYear, dtype: int64

DatabaseWorkedWith
False    10854
True       451
Name: DatabaseWorkedWith, dtype: int64

DatabaseDesireNextYear
False    10271
True      1034
Name: DatabaseDesireNextYear, dtype: int64

PlatformWorkedWith
False    10901
True       404
Name: PlatformWorkedWith, dtype: int64

PlatformDesireNextYear
False    10773
True       532
Name: PlatformDesireNextYear, dtype: int64

WebFrameWorkedWith
False    9924
True     1381
Name: WebFrameWorkedWith, dtype: int64

WebFrameDesireNextYear
False    9699
True     1606
Name: WebFrameDesireNextYear, dtype: int64

MiscTechWorkedWith
False    9138
True     2167
Name: MiscTechWorkedWith, dtype: int64

MiscTechDesireNextYear
False    9862
True     1443
Name: MiscTechDesireNextYear, dtype: int64

DevEnviron
False    11276
True        29
Name: DevEnviron, dtype: int64

OpSys
False    11271
True        34
Name: OpSys, dtype: int64

Containers
False    11223
True        82
Name: Containers, dtype: int64

BlockchainOrg
False    9004
True     2301
Name: BlockchainOrg, dtype: int64

BlockchainIs
False    8711
True     2594
Name: BlockchainIs, dtype: int64

BetterLife
False    11208
True        97
Name: BetterLife, dtype: int64

ITperson
False    11270
True        35
Name: ITperson, dtype: int64

OffOn
False    11267
True        38
Name: OffOn, dtype: int64

SocialMedia
False    11016
True       289
Name: SocialMedia, dtype: int64

Extraversion
False    11285
True        20
Name: Extraversion, dtype: int64

ScreenName
False    10802
True       503
Name: ScreenName, dtype: int64

SOVisit1st
False    10980
True       325
Name: SOVisit1st, dtype: int64

SOVisitFreq
False    11300
True         5
Name: SOVisitFreq, dtype: int64

SOVisitTo
False    11304
True         1
Name: SOVisitTo, dtype: int64

SOFindAnswer
False    11302
True         3
Name: SOFindAnswer, dtype: int64

SOTimeSaved
False    11256
True        49
Name: SOTimeSaved, dtype: int64

SOHowMuchTime
False    9400
True     1905
Name: SOHowMuchTime, dtype: int64

SOAccount
False    11304
True         1
Name: SOAccount, dtype: int64

SOPartFreq
False    10188
True      1117
Name: SOPartFreq, dtype: int64

SOJobs
False    11299
True         6
Name: SOJobs, dtype: int64

EntTeams
False    11300
True         5
Name: EntTeams, dtype: int64

SOComm
False    11305
Name: SOComm, dtype: int64

WelcomeChange
False    11223
True        82
Name: WelcomeChange, dtype: int64

SONewContent
False    9360
True     1945
Name: SONewContent, dtype: int64

Age
False    11023
True       282
Name: Age, dtype: int64

Gender
False    11233
True        72
Name: Gender, dtype: int64

Trans
False    11182
True       123
Name: Trans, dtype: int64

Sexuality
False    10766
True       539
Name: Sexuality, dtype: int64

Ethnicity
False    10635
True       670
Name: Ethnicity, dtype: int64

Dependents
False    11167
True       138
Name: Dependents, dtype: int64

SurveyLength
False    11286
True        19
Name: SurveyLength, dtype: int64

SurveyEase
False    11291
True        14
Name: SurveyEase, dtype: int64

In [38]:
missing_data = df.isnull()

In [39]:
missing_data['EdLevel'].value_counts()

False    11286
True       112
Name: EdLevel, dtype: int64

In [40]:
missing_data['Country'].value_counts()

False    11398
Name: Country, dtype: int64

Find out how many rows are missing in the column 'WorkLoc'

In [11]:
# your code goes here
missing_data['WorkLoc'].value_counts()

False    11273
True        32
Name: WorkLoc, dtype: int64

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [41]:
df['Employment'].value_counts()

Employed full-time    10968
Employed part-time      430
Name: Employment, dtype: int64

In [42]:
df['UndergradMajor'].value_counts()

Computer science, computer engineering, or software engineering          6953
Information systems, information technology, or system administration     794
Another engineering discipline (ex. civil, electrical, mechanical)        759
Web development or web design                                             410
A natural science (ex. biology, chemistry, physics)                       403
Mathematics or statistics                                                 372
A business discipline (ex. accounting, finance, marketing)                244
A social science (ex. anthropology, psychology, political science)        210
A humanities discipline (ex. literature, history, philosophy)             207
Fine arts or performing arts (ex. graphic design, music, studio art)      161
I never declared a major                                                  124
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

In [43]:
df['ConvertedComp'].value_counts()

2000000.0    138
1000000.0    105
100000.0      99
150000.0      92
120000.0      86
            ...
79183.0        1
20475.0        1
288732.0       1
22056.0        1
19880.0        1
Name: ConvertedComp, Length: 3515, dtype: int64

In [44]:
df['ConvertedComp'].dtypes

dtype('float64')

In [12]:
# your code goes here
df['WorkLoc'].value_counts()

Office                                            6747
Home                                              3559
Other place, such as a coworking space or cafe     967
Name: WorkLoc, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [13]:
#make a note of the majority value here, for future reference
df['WorkLoc'].value_counts().idxmax()

'Office'

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [15]:
# your code goes here
df['WorkLoc'].replace(np.NaN, df['WorkLoc'].value_counts().idxmax(), inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [16]:
# your code goes here
missing_data = df.isnull()
missing_data['WorkLoc'].value_counts()

False    11305
Name: WorkLoc, dtype: int64

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [45]:
# your code goes here
df['CompFreq'].value_counts()

Yearly     6073
Monthly    4788
Weekly      331
Name: CompFreq, dtype: int64

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [46]:
# your code goes here
def total_comp (row):
    if row['CompFreq'] == 'Yearly':
        return row['CompTotal']
    if row['CompFreq'] == 'Monthly':
        return row['CompTotal']*12
    if row['CompFreq'] == 'Weekly':
        return row['CompTotal']*52



# df['NormalizedAnnualCompensation'] =

In [47]:
df['NormalizedAnnualCompensation'] = df.apply(lambda row: total_comp(row), axis=1)

In [48]:
df[['CompFreq', 'CompTotal', 'NormalizedAnnualCompensation']]

      CompFreq  CompTotal  NormalizedAnnualCompensation
0       Yearly    61000.0                       61000.0
1       Yearly   138000.0                      138000.0
2       Yearly    90000.0                       90000.0
3      Monthly    29000.0                      348000.0
4       Yearly    90000.0                       90000.0
...        ...        ...                           ...
11547   Yearly   130000.0                      130000.0
11548   Yearly    74400.0                       74400.0
11549   Yearly   105000.0                      105000.0
11550   Yearly    80000.0                       80000.0
11551      NaN        NaN                           NaN

[11398 rows x 3 columns]

In [49]:
df['NormalizedAnnualCompensation'].median()

100000.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2022-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).